[workspace]
members = [
    "attributes",
    "backtrace",
]

[workspace.metadata.release]
pre-release-commit-message = "chore: Release version {{version}}"
consolidate-commits = true
allow-branch = ["main"]
shared-version = true
